### ISSUE TITLE
Token last_used_at not being updated properly 

### ISSUE THREAD

**Issue by bruno-campos** [adamniedzielski/tiddle#56]
Hello,

I've been using Tiddle using the expiration option, and there is a bug for tokens that expires in less than 1 hour. 

For some reason, it does not update the last_activity_at on every request (maybe to save some db updates), making tokens that expire for example in 30 minutes don't ever refresh because of that. So what happens is that those tokens will expire even right after usage.

It also leaves the last_activity_at with an approximate value instead of the real-time the token was used.

There is a spec for this behavior, and I wonder the reason for that: 
https://github.com/adamniedzielski/tiddle/blob/master/spec/strategy_spec.rb#L39

I will also create a PR removing that in case we can take that out :)

**Comment by adamniedzielski** [comment]
Hey @bruno-campos, thanks for the write-up 💚 

Yes, the reason for updating `last_used_at` only if it wasn't updated in the last hour is to prevent extra database requests. Otherwise we will be making a database call on every request, even GET requests, which is quite nasty. I think that having an approximate value in `last_used_at` is acceptable. This behaviour has been part of this gem since the very beginning.

Expiring tokens were introduced later. I've never considered the case of what happens if `expires_in` is smaller than 1 hour. You're right - there's a bug in this scenario.

**Comment by adamniedzielski** [comment]
I can see that you fixed it for yourself in your fork 👍 👏

**Comment by dapx** [comment]
@adamniedzielski I am experiencing the same difficult, I have to set 15 minutes inactive timeout.

Even that it shouldn't be configurable, I believe it should work with short times.

Could we reduce the interval to 1 minute? Or maybe we could have a replaceable default value.

I wouldn't like to create a fork or something like that.

**Comment by dapx** [comment]
We could add the interval when creating the token as we do with the `expires_in`, if no value provided, we keep the default behavior.
